"""All site content for RJR Home Improvements.

RULES FOR THIS FILE
- Only facts supplied by the business: no invented prices, response times, 24/7 claims,
  guarantees, accreditations, insurance claims, job counts or reviews.
- Reviews are verbatim. Do not edit them.
- Educational copy (what flaunching is, how valleys leak, what planning usually says) is
  written as general guidance and hedged where rules vary.
- {area} and {council} tokens are filled per page by build.py.
"""

# ==========================================================================
# SITE CONFIG — fill the TODOs, then `python3 build.py`
# ==========================================================================
SITE = {
    "name": "RJR Home Improvements",
    "legal_name": "R.J.R Home Improvements Ltd",  # as shown on the Google Business Profile
    "url": "https://rjrhomeimprovements.com",  # live domain: used for canonicals, sitemaps, Open Graph and schema
    "rated_people": "https://www.ratedpeople.com/profile/rjr-home-improvements#reviews-and-ratings",
    "gbp": "https://www.google.com/maps/place/R.J.R+Home+Improvements+Ltd/@52.3927945,-2.0854802,12z/data=!4m10!1m2!2m1!1sRJR+Home+Improvements+Birmingham!3m6!1s0x412794acd43217f:0x6fd2befd8528d0e9!8m2!3d52.3927945!4d-2.0154424!15sCiBSSlIgSG9tZSBJbXByb3ZlbWVudHMgQmlybWluZ2hhbZIBEnJvb2ZpbmdfY29udHJhY3RvcuABAA!16s%2Fg%2F11tcyprr5q?entry=ttu",
    "whatsapp": "447542373810",
    "phone": "07542 373810",
    "phone_intl": "+447542373810",
    "email": None,              # TODO optional: shown in footer, privacy policy and schema once set
    "company_number": "13349077",  # Companies House number, shown in footer + privacy policy
    "registered_office": "246 Court Oak Road, Birmingham B32 2EG",  # from Companies House (vault note); client to confirm
    "ico_number": None,         # TODO optional: ICO registration number
    "rating_label": "Excellent",
    "rating_count": 127,
    "experience_years": 45,
    "lastmod": "2026-09-27",
    "updated_human": "27 September 2026",
    "home_hero": "fascia_b",   # home page hero background (key from IMG); image 12, the gable house
    "credit_name": "APX Digital",
    "credit_url": "https://apxdigital.io",
}

ABOUT = [
    "RJR Home Improvements are here to help! We are a family run business who pride ourselves on high quality workmanship and customer care. We offer a friendly reliable and trustworthy service.",
    "Our high standards and customer satisfaction is of the utmost importance to us. Our skills cover the whole building sector, everything from odd jobs as small as garden & gutter clearances to full refurbishments & replacements from top to bottom of your home.",
    "We have a combined experience of 45 years in the trade which means when you choose RJR you can rest assured that your project is in the best of hands.",
]

TRADES = {
    "Roofer": ["Chimney Building / Repair", "Flat Roof - Installation / Repair", "Guttering and Rainwater Pipe", "Leadwork", "Roof Cleaning", "Roof Insulation", "Slate & Tiled Roof", "Thatched Roof", "Velux / Skylight Window", "Wooden Cladding / Fascias / Soffits", "Zinc / Metal Roof", "uPVC Fascias / Soffits / Cladding"],
    "Blacksmith / Metal worker": ["Zinc / Metal Roof"],
    "Bricklayer": ["Chimney Building / Repair", "Garden Wall", "Pizza Oven", "Pointing / Repointing", "Stonework / Stone Cladding"],
    "Builder": ["Cavity Wall Insulation", "Chimney Building / Repair", "Cladding", "Garage Conversion", "Home Improvements", "House Extension", "Loft Conversion", "Mould / Damp Control"],
}

# ==========================================================================
# REVIEWS — verbatim from Rated People
# ==========================================================================
REVIEWS = [
    {"id": "ann-b17", "name": "ann", "pc": "B17", "date": "2025-10-23", "disp": "23 Oct 2025",
     "text": "Ryan was punctual at all times. His communication skills are excellent. Ryan and the team worked efficiently and effectively. The finish on the job was good. I believe that he diagnosed correctly the problem with the roof. I can't confirm yet whether the leak has been resolved. I'll have to wait until it rains!"},
    {"id": "john-wv4", "name": "john", "pc": "WV4", "date": "2025-10-22", "disp": "22 Oct 2025",
     "text": "contact with ryan was smooth, arrived to look at job completed said job and cleaned up any mess afterwards very professional and curteous"},
    {"id": "john-b31", "name": "John", "pc": "B31", "date": "2025-09-30", "disp": "30 Sept 2025", "text": None},
    {"id": "lewis-b30", "name": "Lewis", "pc": "B30", "date": "2025-09-25", "disp": "25 Sept 2025",
     "text": "Ryan got in touch really quickly and came round a few hours later. Fixed the persistent leak we've had for a good price. Considering we'd previously been told we need to get our neighbours to replace their gutters too, and we'd need scaffolding, I was pleasantly surprised how straightforward he made it."},
    {"id": "matthew-b90", "name": "Matthew", "pc": "B90", "date": "2025-09-08", "disp": "8 Sept 2025",
     "text": "Ryan and his team did great work. The team were done quickly and sorted everything from getting scaffold though to clearing the waste. Very professional and I would recommend them for any roofing work."},
]

# Short verbatim extracts for single-line proof on inner pages (never paraphrased)
QUOTES = {
    "fast": ("Ryan got in touch really quickly and came round a few hours later.", "lewis-b30"),
    "leak": ("Fixed the persistent leak we've had for a good price.", "lewis-b30"),
    "diagnosis": ("I believe that he diagnosed correctly the problem with the roof.", "ann-b17"),
    "tidy": ("arrived to look at job completed said job and cleaned up any mess afterwards", "john-wv4"),
    "scaffold": ("sorted everything from getting scaffold though to clearing the waste.", "matthew-b90"),
    "finish": ("The finish on the job was good.", "ann-b17"),
    "roofing": ("I would recommend them for any roofing work.", "matthew-b90"),
    "gutters": ("I was pleasantly surprised how straightforward he made it.", "lewis-b30"),
}

# ==========================================================================
# IMAGES — key: (source file in /images, alt text, focal point for crops)
# ==========================================================================
IMG = {
    "chim_b1": ("chimney-before-front.jpg", "Brick chimney stack before repair, with eroded mortar joints, displaced bricks, lichen, a metal strap band and a cracked stone pot", "50% 45%"),
    "chim_b2": ("chimney-before-side.jpg", "Side view of the same chimney before repair, showing open joints, plant growth and a TV aerial bracket fixed to the stack", "45% 45%"),
    "chim_a": ("chimney-after.jpg", "The same chimney stack after repair, with rebuilt oversailing courses, fresh pointing, new flaunching and a new terracotta pot", "56% 45%"),
    "velux_d": ("velux-extension-during.jpg", "Single-storey rear extension roof stripped to new breathable membrane and battens, with the opening framed for a roof window", "50% 52%"),
    "velux_a": ("velux-extension-after.jpg", "The same extension roof re-covered in pantiles with a new Velux roof window and lead flashing along the wall", "40% 58%"),
    "fascia_b": ("gable-fascias-before.webp", "Detached house before work, with black gable trims, black gutters and downpipes, and scaffolding at both gable ends", "50% 45%"),
    "fascia_a": ("gable-fascias-after.webp", "The same house after work, with new white decorative uPVC bargeboards on the gables and white fascias, gutters and downpipes", "55% 40%"),
    "tile_a": ("reroof-concrete-tiles.jpg", "Pitched roof newly re-covered in grey concrete tiles laid to straight courses", "50% 50%"),
    "tile_v": ("reroof-gable-verge.jpg", "Gable verge on the same new grey tile roof, bedded in mortar along the brick gable", "75% 25%"),
    "canopy_d": ("canopy-roof-stripping.webp", "Roofer stripping old clay tiles from a canopy roof over a garage door", "35% 40%"),
    "leanto_d": ("lean-to-porch-framing.jpg", "Two builders fixing the timber frame for a new lean-to porch roof across the front of two terraced houses", "50% 58%"),
}

# One job per sequence, verified from the photos (same building, same details).
PROJECTS = {
    "chimney": {
        "title": "Chimney stack rebuild & repoint", "service": "chimney-repair", "ratio": "4 / 5",
        "intro": "A stepped brick stack that had lost most of its mortar. Same stack, same lead soakers, same roof, photographed from the scaffold.",
        "seq": [("Before", "chim_b1", "Open joints, displaced bricks, lichen, a strap band round the top, cracked stone pot."),
                ("Before", "chim_b2", "Side face: plant growth in the joints, aerial bracket fixed to the stack."),
                ("After", "chim_a", "Oversailing courses rebuilt, stack repointed, new flaunching and terracotta pot.")],
    },
    "fascias": {
        "title": "Gable bargeboards, fascias & guttering", "service": "fascias-soffits", "ratio": "4 / 3",
        "intro": "A detached house with three front gables. Same house, same windows and nameplate, before and after.",
        "seq": [("Before", "fascia_b", "Black gable trims, black gutters and downpipes; scaffold at both gable ends."),
                ("After", "fascia_a", "White decorative uPVC bargeboards on every gable; white fascias, gutters and downpipes.")],
    },
    "velux": {
        "title": "Extension roof with a new Velux window", "service": "velux-windows", "ratio": "1 / 1",
        "intro": "A single-storey rear extension roof stripped, re-battened and re-covered, with a roof window added. Same extension, same windows above.",
        "seq": [("During", "velux_d", "Stripped to new breathable membrane and battens; opening framed for the window."),
                ("After", "velux_a", "Re-covered in matching pantiles, new Velux window, lead flashing along the wall.")],
    },
    "reroof": {
        "title": "Re-roof in grey concrete tiles", "service": "roof-repairs", "ratio": "4 / 3",
        "intro": "One re-roof, two views: the finished slope and the verge along the gable.",
        "seq": [("Completed", "tile_a", "New tiles laid to straight, even courses down to the eaves."),
                ("Completed", "tile_v", "Verge bedded in mortar along the brick gable of the same roof.")],
    },
    "canopy": {
        "title": "Canopy roof strip", "service": "roof-repairs", "ratio": "4 / 3",
        "intro": "Old clay tiles coming off a canopy roof above a garage door, with the timber bargeboards exposed.",
        "seq": [("During", "canopy_d", "Tiles stripped by hand, working from the roof.")],
    },
    "leanto": {
        "title": "New lean-to porch roof", "service": "building-work", "ratio": "3 / 4",
        "intro": "A new timber-framed lean-to roof spanning the front doors of two terraced houses.",
        "seq": [("During", "leanto_d", "Two of the team fixing the wall plate, rafters and front bearer.")],
    },
}

# ==========================================================================
# HOUSING FEATURES — what the roofs in an area are actually like.
# Area pages and area × service pages are composed from these, so each page's
# advice changes with the local housing, not just the place name.
# ==========================================================================
FEATURES = {
    "slate": ("Natural slate roofs", "Thin split stone on Victorian and Edwardian roofs. Watch for slipped slates, nail fatigue and worn lead at valleys and abutments."),
    "clay": ("Clay plain tiles", "Small clay tiles on many interwar and older roofs. Frost can crack them, and older roofs often have no membrane underneath."),
    "concrete": ("Concrete interlocking tiles", "Heavy, durable tiles common on post-war homes and re-roofs. Problems tend to be at ridges, verges and flashings rather than mid-slope."),
    "dryfix": ("Dry ridge and dry verge systems", "Mechanically fixed caps on newer roofs. Loose or missing caps leave tile edges open to the weather."),
    "stacks": ("Tall chimney stacks", "Exposed stacks with several pots, where pointing, flaunching and flashing take the weather."),
    "shared_stacks": ("Shared party-wall stacks", "Stacks shared between neighbours, where a repair can involve both houses."),
    "outriggers": ("Back additions and valleys", "Rear additions on terraces create valleys between neighbouring roofs, a frequent leak point."),
    "parapets": ("Parapet and box gutters", "Hidden gutters behind roof-edge walls, lined with lead or membrane, which leak into the walls when blocked."),
    "hips": ("Hipped roofs", "Roofs that slope on every side, with long mortar-bedded hip and ridge lines."),
    "canopies": ("Porch and bay canopies", "Small roofs over bays and front doors, each with its own flashing to the wall."),
    "flat_ext": ("Flat-roofed extensions and dormers", "Kitchen extensions, dormers and additions with flat coverings, where edges and wall abutments fail first."),
    "garages": ("Flat-roofed garages", "Garage roofs, often felt, many of them past their best."),
    "trees": ("Mature trees", "Leaf fall blocks gutters and valleys, and storms bring branches down."),
    "conservation": ("Conservation areas", "Visible roof work is expected to match the original materials; changes may need consent."),
    "rented": ("Rented homes", "Leaks left alone quickly become damp and mould problems for tenants."),
}

# FEATURE_NOTES[service][feature] = (question, answer). Only rendered where an area has that feature.
FEATURE_NOTES = {
    "emergency-roof-repairs": {
        "slate": ("Can a slipped slate be refixed in an emergency?", "Usually. A single slipped slate can be refitted with a slate hook or a lead or copper strip without disturbing the slates around it. Where several have gone at once it can point to nail fatigue across the slope, which is worth checking once the leak is stopped."),
        "clay": ("Can old clay tiles be matched in a hurry?", "Clay plain tiles vary in size and colour by age and maker, so a perfect match can mean reclaimed tiles. In an emergency, making the roof watertight comes first; the permanent repair can then use matched tiles."),
        "concrete": ("Where does a concrete tile roof fail in bad weather?", "Concrete tiles are heavy and rarely lift mid-slope. The weak points are the edges and details: mortar ridges and verges, and tiles cut around vents and roof windows."),
        "dryfix": ("The plastic caps on my roof edge have come loose. Is that urgent?", "It can be. Dry verge and dry ridge caps clip or screw into place; once one works loose it can blow off and leave the tile edges open. Loose caps can usually be refixed or replaced without disturbing the rest of the roof."),
        "stacks": ("Is a damaged chimney an emergency?", "If bricks or a pot are loose, yes: they can fall. Keep people and cars away from underneath. Cracked flaunching on its own isn't dangerous, but it lets water down the flue and into the chimney breast."),
        "shared_stacks": ("The leak is from a chimney we share with next door. Who fixes it?", "A stack on the party wall usually serves both houses, so a lasting repair is normally agreed between both owners. In an emergency the priority is making it safe and watertight; we'll show you what we find so you can share it with your neighbour."),
        "outriggers": ("Why does water appear at the back of the house in heavy rain?", "On terraces with back additions, the valley between your rear roof and your neighbour's collects water from both slopes. If it's blocked or its lining has failed, it overflows into the walls and ceilings at the back."),
        "parapets": ("Water is running down inside a wall. Could it be a hidden gutter?", "Yes. A parapet or box gutter sits behind a low wall at the roof edge. When its outlet blocks or its lining splits, water builds up and spills into the wall instead of over the edge."),
        "hips": ("Ridge or hip tiles came off in the wind. Is that urgent?", "Yes. Loose tiles can fall, and the gap lets rain straight into the roof. On older roofs these tiles are held only by mortar, which loses its grip over time."),
        "canopies": ("Water is coming in above the front door. Is it the porch roof?", "Often. Porch and bay roofs have their own flashing where they meet the wall. When that fails, water runs down inside the wall and shows up around the door or bay window."),
        "flat_ext": ("Can a leaking flat roof on an extension be patched in an emergency?", "A split or lifted edge can usually be patched to stop the water. If the deck underneath has gone soft, the patch only buys time and the covering and boards will need replacing."),
        "garages": ("The garage roof is leaking onto everything stored inside. What now?", "Move what you can, and photograph the ceiling and the roof from the ground. Garage felt roofs often fail at the edges and around outlets; a split can be patched, but a soft deck means replacement."),
        "trees": ("A branch hit the roof. What should I check?", "From the ground, look for cracked or displaced tiles or slates, crushed gutters and anything hanging loose. Check the loft for daylight or damp. Don't climb up; photograph what you can see and send it over."),
        "conservation": ("Can emergency repairs go ahead in a conservation area?", "Making a roof safe and watertight doesn't wait for paperwork. The permanent repair should match the original materials; like-for-like repairs normally don't need consent, but changes to materials or appearance might."),
        "rented": ("I'm a landlord and a tenant has reported a roof leak. What now?", "Ask the tenant for photos and move quickly: leaks in rented homes turn into damp and mould fast. Send the photos, the postcode and who to contact for access."),
    },
    "storm-damage": {
        "slate": ("Why do slates slide after a storm?", "Wind lifts the lower edge of each slate, and if the nails have corroded (nail fatigue) they give way. One slipped slate after a storm often means others on the same slope are close to going."),
        "clay": ("Plain tiles have slipped after high winds. Why?", "Plain tiles hang on small nibs and are nailed only in some courses. When nibs break or battens soften, wind pulls tiles out of place. Replacing them with matched tiles keeps the roof uniform."),
        "concrete": ("What storm damage should I expect on a concrete tile roof?", "Concrete tiles rarely blow off mid-slope. Storm damage usually shows at ridges, hips and verges, where cracked mortar bedding lets tiles lift."),
        "dryfix": ("Our dry verge caps blew off in the storm. Can they be replaced?", "Usually, yes. Caps are made to fit particular tile profiles, so replacements are matched to the system on your roof and fixed back in place."),
        "stacks": ("What does a storm do to a chimney?", "High winds can crack or dislodge pots, loosen weakened brickwork at the top of the stack, and lift the lead flashing at its base. A stack that has moved or has loose bricks needs making safe quickly."),
        "shared_stacks": ("Our shared chimney was damaged in the storm. Does insurance cover it?", "Many buildings policies cover storm damage to chimneys. Where a stack is shared, both owners' insurers may be involved, so photograph both sides if you can."),
        "outriggers": ("Why does storm debris in the back valley matter?", "Leaves and broken tile fragments collect in the valleys between back roofs and block them. The next heavy rain then overflows into the house."),
        "parapets": ("Parapet walls took a battering. What should be checked?", "The copings on top and the gutter lining behind. Loose copings can fall, and a displaced lining lets water into the wall."),
        "hips": ("Why do hip and ridge tiles come off first?", "They sit on the most exposed lines of the roof and, on older roofs, are held only by mortar. Once the mortar cracks, wind can lift them off in one go."),
        "canopies": ("Do porch and bay roofs get storm damaged?", "Yes. They're small, low and exposed, and the flashing where they meet the wall is often the first thing wind lifts."),
        "flat_ext": ("Can wind damage a flat roof?", "Yes. Wind gets under loose edges and can peel back felt or membrane. Edge trims and upstands are the parts to check after a storm."),
        "garages": ("The garage roof covering has lifted. Can it be stuck back down?", "A small lifted edge can sometimes be re-bonded. If the covering has torn or water has got into the deck, replacement is the lasting fix."),
        "trees": ("Branches came down on the roof. What's usually damaged?", "Broken tiles or slates, crushed gutters and split flat roof coverings. Hidden damage under the impact point is common, so check the loft for daylight or damp."),
        "conservation": ("Do storm repairs in a conservation area need matching materials?", "Permanent repairs should match what's there: natural slate for slate, clay for clay. Temporary measures to keep water out can go on first."),
        "rented": ("How should a landlord record storm damage?", "Get dated photos from the tenant or on your first visit, keep any fallen tiles, and note when the damage appeared. It helps with the insurance claim and your own records."),
    },
    "roof-leaks": {
        "slate": ("Why does a slate roof leak when no slates are missing?", "Slates can crack at a nail hole or slide just far enough to open a gap. Nail fatigue, split lead at valleys and abutments, and worn ridge mortar are the usual causes."),
        "clay": ("Why is my clay tile roof leaking?", "Clay tiles can laminate or crack with frost, and ridge and verge mortar erodes. Many older roofs also have no membrane under the tiles, so any gap lets water straight in."),
        "concrete": ("The concrete tiles look fine, so where's the leak?", "Usually at the details: cracked ridge mortar, failed flashing, or tiles cut around vents and roof windows. Older concrete tiles can also become porous as their surface wears."),
        "dryfix": ("Can dry ridge and dry verge systems leak?", "They can if caps come loose, seals perish or the ridge roll underneath is damaged. Checking and refixing the caps is normally straightforward."),
        "stacks": ("Could my chimney be causing the leak?", "Very often. Water gets in through failed flashing where the stack meets the roof, through eroded pointing, through cracked flaunching, or straight down an uncapped flue."),
        "shared_stacks": ("Damp on the chimney breast: whose side is the problem on?", "On a shared stack the fault can be on either side of the party wall. The flashing and pointing on both sides need checking to find where the water gets in."),
        "outriggers": ("Why is the leak at the back of the house?", "The valley between back additions carries water from two roofs. A blocked outlet or split lining there is one of the most common leaks on terraced streets."),
        "parapets": ("Water shows up a floor below the roof. Could it be a hidden gutter?", "Yes. Parapet and box gutters sit behind the roof edge; when the outlet blocks or the lining splits, water runs into the wall and can surface well below the roof."),
        "hips": ("Is my leak coming from the ridge or a hip?", "If the stain is near the top of the roof or along a hip line, cracked mortar bedding under the ridge or hip tiles is a likely cause. Re-bedding or a dry-fixed system stops it."),
        "canopies": ("There's a leak around the bay window or front door. Why?", "The small roof over a bay or porch has its own flashing to the wall. When it fails, water runs down behind the flashing and appears around the window head or door frame."),
        "flat_ext": ("Why does the leak show up where the extension meets the house?", "The joint relies on an upstand and flashing. If either fails, water runs down the wall face and into the ceiling below the join."),
        "garages": ("The garage leaks in several places. Is the whole roof gone?", "Multiple leaks on a felt garage roof usually mean the covering has reached the end of its life, and often the deck has softened too. Replacing both is more economical than chasing each leak."),
        "trees": ("Could nearby trees be causing my leak?", "Indirectly, yes. Leaves and moss block gutters, outlets and valleys, so water backs up under the roof edge. Regular clearing costs far less than the repairs it prevents."),
        "conservation": ("Will fixing a leak in a conservation area change how my roof looks?", "It shouldn't. Leak repairs on visible roofs should match the existing materials and details."),
        "rented": ("A tenant reports mould in a top-floor room. Could it be the roof?", "It could be a slow leak rather than condensation. A patch that grows after rain, or damp at the ceiling edge, points to the roof, gutter or flashing."),
    },
    "roof-repairs": {
        "slate": ("Repair or re-roof a slate roof?", "If the slates are sound and the problem is local (a few slipped slates, a valley, a ridge), repair makes sense. Widespread nail fatigue, many cracked or delaminating slates, or rotten battens point to stripping and re-slating, often reusing the sound slates."),
        "clay": ("Can a clay tile roof be repaired with matching tiles?", "Usually, with reclaimed or closely matched tiles. On older roofs without a membrane, re-roofing adds a breathable membrane and new battens."),
        "concrete": ("Does a worn concrete tile roof need replacing?", "Not always. Many need only ridge, verge and local tile repairs. A full re-roof is for when tiles are widely worn or the battens and membrane have failed, like the grey tile re-roof on this page."),
        "dryfix": ("Can mortar ridges be swapped for a dry ridge system?", "On many tiled roofs, yes. Cracked mortar ridges and verges can be replaced with mechanically fixed dry systems that don't rely on mortar."),
        "hips": ("Why do hip tiles keep coming loose?", "The mortar under them has lost its bond. Re-bedding in fresh mortar, or fitting a dry hip system with fixings, secures them properly."),
        "canopies": ("Can the porch or bay roof be re-tiled on its own?", "Yes. Porch, bay and canopy roofs can be stripped and re-covered separately, with new flashing where they meet the wall."),
        "outriggers": ("Can the back addition roof be done separately?", "Yes. Rear addition roofs are often in worse condition than the main roof because of their valleys, and can be re-covered on their own."),
        "parapets": ("Should the parapet gutters be done with the roof?", "If the roof is being re-covered, it's the right time to re-line parapet and box gutters, while the scaffolding is already up."),
        "trees": ("Is moss damaging my roof?", "Heavy moss holds water, lifts tile edges and blocks gutters. It can be cleared, and the tiles underneath checked at the same time."),
        "conservation": ("What does like-for-like mean on a conservation-area roof?", "Matching the original covering (natural slate for slate, clay for clay) along with details such as ridge tiles and finials. Changing materials or appearance may need consent."),
        "rented": ("Should a landlord repair or re-roof?", "It depends on the roof's condition, not the tenancy. A sound roof with local faults needs repair; a roof with widespread failure will keep generating callouts until it's re-covered."),
    },
    "chimney-repair": {
        "stacks": ("Why are tall stacks more prone to damage?", "They're more exposed to wind and driving rain, so pointing and flaunching erode faster at the top, and a tall stack with weakened mortar can start to lean."),
        "shared_stacks": ("Can I repair my side of a shared chimney?", "Work on a shared stack affects both houses, so it's normally agreed with your neighbour. Some work on party structures comes under the Party Wall etc. Act 1996; if in doubt, check before work starts."),
        "slate": ("Where a stack meets a slate roof, what's the weak point?", "The lead soakers and step flashing. When the lead splits or pulls out of its mortar joint, water tracks down into the chimney breast."),
        "clay": ("The flashing round my chimney has been sealed with mastic. Is that OK?", "Mastic and flashing tape are short-term fixes. Properly dressed lead flashing, tucked into the mortar joint, lasts far longer."),
        "concrete": ("Why is there a gap between the tiles and the chimney?", "Interlocking tiles are thick, so the flashing has to be shaped over their profile. If it was cut short or has lifted, rain gets straight in beside the stack."),
        "hips": ("Our chimney isn't used. Does it still need maintaining?", "Yes. An unused stack still needs sound pointing, flaunching and flashing, and a capped flue with some ventilation to stop damp."),
        "outriggers": ("There's a second chimney on the back addition. Does it matter?", "Many terraces have a smaller stack on the rear addition. It gets less attention than the front one and is often in worse condition."),
        "conservation": ("Can a chimney be rebuilt in a conservation area?", "Rebuilding like for like, with matching bricks and details, is what's normally expected. Removing or lowering a stack visible from the street may need consent."),
        "trees": ("Can trees cause chimney problems?", "Overhanging branches can knock pots in high winds, and constant shade keeps brickwork damp, so moss and lichen take hold and mortar erodes faster."),
        "rented": ("Is a damp chimney breast in a rental a roof problem?", "Often. Failed flashing, eroded pointing or an open flue let water into the breast. It's worth ruling these out before treating it as condensation."),
    },
    "flat-roofs": {
        "flat_ext": ("What usually fails on a flat-roofed extension?", "The edges. Most leaks start at the upstand and flashing against the house wall, or at the trim along the gutter edge. Standing water in the middle speeds up wear on felt."),
        "outriggers": ("Flat roof on a terrace back addition: what's different?", "Many terrace kitchen extensions abut the neighbour's wall as well as your own, so the flashing on that side matters just as much."),
        "canopies": ("Can a flat roof over a bay or porch be re-covered?", "Yes. Small flat roofs over bays and porches are quick to strip and re-cover, and it's the moment to renew the edge trim and wall flashing."),
        "garages": ("Is it worth replacing a flat garage roof?", "Many garage roofs are old felt on boards that have softened. Replacing the deck and covering together usually beats patching again and again."),
        "parapets": ("Are there flat sections behind the parapet?", "On larger period houses there often are: flat areas and gutters hidden behind the parapet, needing clear outlets and a sound lining like any flat roof."),
        "conservation": ("Flat roof on a period house in a conservation area?", "Rear flat roofs out of view are usually straightforward. Visible ones, such as bay tops, may call for lead or a finish that suits the period."),
        "trees": ("Why do leaves matter on a flat roof?", "They block outlets and hold water on the roof. Keeping outlets clear stops ponding and extends the life of the covering."),
        "rented": ("Flat roof leaking in a rental: repair or replace?", "A single split can be repaired. Repeated leaks, ponding and a soft deck mean the covering is finished, and replacing it stops the repeat callouts."),
    },
}

# ==========================================================================
# SERVICES — deep pages. `matrix: True` = also gets a page in every area.
# ==========================================================================
SERVICES = [
    {
        "slug": "emergency-roof-repairs", "trade": "Roofer", "matrix": True, "emergency": True, "hero": "canopy_d",
        "name": "Emergency roof repairs", "h1": "Emergency roof repairs", "kw": "Emergency Roofer",
        "summary": "Leaks, storm damage, fallen tiles and chimney problems that can't wait.",
        "cta": "Leak happening now? Send us a photo.",
        "answer": "If your roof is leaking or damaged in {area}, WhatsApp a photo of the problem and your postcode to RJR Home Improvements. We make the roof safe and watertight, then find and fix the cause: slipped tiles, storm damage, failed flashing, damaged chimneys or flat roof failures.",
        "intro": ["A roof emergency is anything letting water into your home now, or anything that could fall. The first job is to make it safe and stop the water. The second is to find the cause, which is often not directly above the stain on your ceiling.",
                  "Emergencies are what most people first call a roofer for, and they're where experience matters most. Diagnosis is the skill: one B17 customer wrote that Ryan “diagnosed correctly the problem with the roof”."],
        "causes": [("Slipped or missing tiles and slates", "Wind, corroded nails or broken nibs let them slide, opening a gap straight into the roof."),
                   ("Failed flashing", "Lead or mortar where the roof meets a chimney or wall cracks, splits or lifts."),
                   ("Blocked valleys and gutters", "Water backs up under the tiles or overflows into the walls."),
                   ("Chimney damage", "Loose pots, cracked flaunching and eroded pointing let water down the stack."),
                   ("Flat roof failure", "Splits, blisters and lifted edges on felt and older coverings.")],
        "process": [("Send photos", "WhatsApp photos of the damage inside and out, with your postcode, so we can see what we're dealing with before we arrive."),
                    ("Make safe", "Loose tiles, slates or chimney pots are secured or removed, and the roof is made watertight."),
                    ("Find the cause", "We trace where the water is actually getting in, not just where it shows."),
                    ("Repair properly", "The permanent repair is agreed with you and matched to your roof's materials."),
                    ("Record it", "Photos of the damage and the repair help with any insurance claim.")],
        "cost_factors": ["Access: whether ladders are enough or scaffolding is needed", "The height and pitch of the roof", "How much of the roof is affected", "Matching materials such as reclaimed slates or clay tiles", "Whether water has damaged the timbers underneath"],
        "prevent": ["Keep gutters, valleys and outlets clear, especially after autumn leaf fall", "Look at the roof from the ground after high winds", "Deal with slipped tiles and cracked flaunching while they're small jobs", "Check the loft after heavy rain for damp patches or daylight"],
        "includes": ["Active roof leaks", "Storm and wind damage", "Slipped, cracked or missing tiles and slates", "Ridge and hip tiles blown loose", "Damaged chimney stacks, pots and flaunching", "Lifted or missing lead flashing", "Overflowing gutters and valleys"],
        "signs": ["Water coming through a ceiling or light fitting", "Tiles, slates or ridge tiles on the ground after wind", "A chimney pot or bricks loose or fallen", "Daylight visible in the loft", "A ceiling bulging with trapped water"],
        "faqs": [
            ("What should I do if my roof is leaking right now?", "Put a bucket under the drip and move furniture and valuables away. If water is near light fittings or sockets, switch that circuit off at the consumer unit. If a ceiling is bulging, keep people out from under it. Don't go up on the roof yourself. Take photos, then WhatsApp them to us with your postcode."),
            ("How quickly can you get to a roof emergency in {area}?", "It depends on the day's jobs and the weather. Send photos on WhatsApp and we'll come back to you about when we can get there. One B30 customer wrote that Ryan “got in touch really quickly and came round a few hours later”."),
            ("Will you fix the cause, or just patch it?", "The aim is to find and fix the cause. If a temporary repair is needed first, for example while matching slates are sourced, we'll explain what's temporary and what the permanent repair involves."),
            ("What should I send with my WhatsApp message?", "Photos of the damage inside and of the roof from the ground, your postcode, and when the problem shows up, such as only in heavy rain or only in wind."),
            ("Is storm damage covered by home insurance?", "Many buildings insurance policies cover storm damage, but wear and tear usually isn't, so check your policy. Photos taken before any work starts help with a claim."),
        ],
        "projects": ["chimney"], "quote": "diagnosis",
    },
    {
        "slug": "storm-damage", "trade": "Roofer", "matrix": True, "emergency": True, "hero": "chim_b1",
        "name": "Storm damage repairs", "h1": "Storm damage roof repairs", "kw": "Storm Damage Roof Repairs",
        "summary": "Tiles, ridges, chimneys, flashing and gutters damaged by wind and rain.",
        "cta": "Storm hit the roof? Show us the damage.",
        "answer": "After high winds or heavy rain in {area}, RJR Home Improvements repairs what storms do to roofs: slipped and missing tiles and slates, ridge and hip tiles blown loose, damaged chimney pots and stacks, lifted lead flashing, and gutters and fascias pulled away.",
        "intro": ["Storms find the weak points a roof already has. Mortar that has been cracking for years finally lets go of a ridge tile; a slate hanging on a corroded nail finally slides. That's why storm damage is rarely just one tile.",
                  "The job is to make the roof safe and dry, then check the rest of it for damage that hasn't shown yet."],
        "causes": [("Wind uplift", "Gusts get under tile and slate edges, ridge caps and flat roof trims, and lift them."),
                   ("Failed mortar", "Ridges, hips and verges bedded in old mortar are the first things to go."),
                   ("Falling debris", "Branches and chimney pots crack tiles and crush gutters."),
                   ("Driving rain", "Horizontal rain gets past slipped tiles and lifted flashing that normal rain wouldn't.")],
        "process": [("Check from the ground", "Photos from the ground and inside show us where to look first."),
                    ("Make safe", "Anything loose that could fall is secured or taken down, and gaps are made watertight."),
                    ("Check the whole roof", "Storms rarely damage one spot, so the rest of the roof is checked too."),
                    ("Repair", "Tiles, slates, ridges, flashing and gutters are repaired to match the existing roof."),
                    ("Photograph", "Before and after photos support any insurance claim.")],
        "cost_factors": ["Scaffolding, if the damage is high or widespread", "How many tiles, slates or ridge tiles need replacing", "Whether the chimney needs making safe or rebuilding", "Matching materials to the existing roof", "Hidden damage to battens or timbers"],
        "prevent": ["Re-bed or dry-fix tired ridges and hips before winter", "Have chimney pots and flaunching checked", "Get overhanging branches cut back by a tree surgeon", "Clear gutters and valleys before stormy seasons"],
        "includes": ["Replacing blown-off or slipped tiles and slates", "Re-bedding or re-fixing ridge and hip tiles", "Chimney pots, flaunching and stacks", "Lead flashing lifted by wind", "Gutters, fascias and bargeboards pulled away", "Checking the rest of the roof for hidden damage"],
        "signs": ["Tiles or slates in the garden after wind", "Gaps in the ridge line", "A chimney pot missing or leaning", "Flashing flapping or lifted", "New damp patches after a storm"],
        "faqs": [
            ("What should I check after a storm?", "From the ground: the ridge line, the chimney and its pots, the edges of the roof, and the gutters. Inside: the ceilings of top-floor rooms and, if it's safe, the loft for damp or daylight."),
            ("Is it safe to stay in the house after storm damage to the roof?", "If a chimney stack is leaning or bricks have fallen, keep people and cars away from where more could fall, and stay out of rooms with bulging or cracked ceilings. If there's immediate danger, call 999."),
            ("Can storm damage show up later?", "Yes. A tile can slip without leaking until the next heavy rain, and water can soak into insulation for days before a stain appears. It's worth checking after any big storm."),
            ("Will my insurer want photos of storm damage in {area}?", "Usually. Photograph the damage from the ground and inside before any work starts, and keep any fallen tiles or pots."),
            ("Why do ridge tiles come off in storms?", "Ridge tiles on older roofs are bedded in mortar, which cracks and loses grip over time. Wind then lifts them. Re-bedding in fresh mortar, or a mechanically fixed dry ridge system, secures them."),
        ],
        "projects": ["chimney", "reroof"], "quote": "scaffold",
    },
    {
        "slug": "roof-leaks", "trade": "Roofer", "matrix": True, "emergency": True, "hero": "velux_d",
        "name": "Roof leak repairs", "h1": "Roof leak repairs", "kw": "Roof Leak Repairs",
        "summary": "Tracing and fixing leaks in pitched roofs, flat roofs, chimneys and gutters.",
        "cta": "Got a stain that keeps coming back? Let's find the source.",
        "answer": "RJR Home Improvements traces and fixes roof leaks in {area}. Water often travels along timbers before it shows on a ceiling, so the leak is rarely right above the stain. The usual sources are slipped tiles, failed valleys, chimney flashing, flat roof edges and blocked gutters.",
        "intro": ["The hardest part of a leak is finding it. Water gets in at one point, runs along a batten, a rafter or the top of a wall, and drips out somewhere else. Patching where the stain is rarely works for long.",
                  "Finding the source means reading the clues (when it leaks, where the stain is, what's above it) and then checking the roof details in order."],
        "causes": [("Valleys", "Where two slopes meet, water from both runs through one channel. Blocked or split valleys leak heavily."),
                   ("Flashing", "The lead or mortar seal where the roof meets a chimney or wall."),
                   ("Chimneys", "Eroded pointing, cracked flaunching and open flues."),
                   ("Ridges and hips", "Cracked mortar bedding along the top and edges of the roof."),
                   ("Flat roof edges", "Upstands, trims and outlets on extensions and garages."),
                   ("Roof windows", "Failed flashing kits and seals around Velux and skylights."),
                   ("Gutters", "Blocked or back-falling gutters pushing water behind the fascia.")],
        "leak_vs_condensation": "A leak follows the weather: it appears after rain, gets worse in wind-driven rain, and leaves tide-marked stains. Condensation follows the temperature: it shows in cold weather, often as damp across the underside of the roof or droplets on nails, whether or not it has rained.",
        "process": [("Read the clues", "When does it leak? Only in heavy rain, only with wind from one direction, or all the time?"),
                    ("Check inside", "Where the stain is, and what's directly above and uphill of it in the loft."),
                    ("Check the details", "Valleys, flashing, chimney, ridge, roof windows and gutters, in order."),
                    ("Fix the source", "Repair the detail that's letting water in, not the stain."),
                    ("Make good", "Replace damaged battens, membrane or insulation where water has soaked them.")],
        "cost_factors": ["How hard the source is to find and reach", "Whether scaffolding is needed", "The detail involved: a slipped tile is quicker than a valley or chimney", "Damage to timbers, insulation or ceilings", "Matching materials"],
        "prevent": ["Clear gutters, outlets and valleys at least once a year", "Keep an eye on chimney flashing and flaunching", "Replace slipped tiles promptly, before water gets under them", "Check flat roof edges and outlets each spring"],
        "includes": ["Leak tracing on pitched and flat roofs", "Chimney and wall flashing leaks", "Valley and gutter leaks", "Flat roof splits and failed seams", "Leaks around Velux and roof windows", "Repairing the cause, then making good"],
        "signs": ["Brown rings on ceilings", "Drips after rain", "A damp chimney breast", "Wet loft insulation or timbers", "Mould in top-floor rooms"],
        "faqs": [
            ("Is it a leak or condensation?", "A leak follows the weather and appears after rain. Condensation follows the temperature, showing in cold spells whether or not it has rained, often as damp across the underside of the roof."),
            ("Why does my roof only leak in heavy rain or wind?", "Driving rain gets pushed under slipped tiles, through failed flashing or back up a blocked gutter, when light rain drains away normally. That points to specific details that can be checked."),
            ("My leak was fixed before and came back. Why?", "Usually because the symptom was treated rather than the source. A B30 customer had been told the fix needed scaffolding and new gutters on their neighbours' house; Ryan “fixed the persistent leak we've had for a good price”."),
            ("Can a leak in {area} be fixed without scaffolding?", "Sometimes. Some leaks can be reached safely from ladders and roof ladders; chimney work and larger repairs usually need scaffolding. We'll say which once we've seen photos or the roof."),
            ("Will the ceiling need repairing too?", "If water has soaked the plasterboard or it's stained, it may need replacing once the leak is fixed and the ceiling has dried out."),
        ],
        "projects": ["velux"], "quote": "leak",
    },
    {
        "slug": "roof-repairs", "trade": "Roofer", "matrix": True, "hero": "tile_a",
        "name": "Roof repairs & re-roofing", "h1": "Roof repairs & re-roofing", "kw": "Roof Repairs & Re-roofing",
        "summary": "Slate and tiled roofs: slipped tiles, ridges, valleys and full re-roofs.",
        "cta": "Repair or re-roof? Send photos and we'll tell you which.",
        "answer": "RJR Home Improvements repairs, re-tiles and re-slates pitched roofs in {area}: slipped, cracked or missing tiles and slates, ridges, hips, verges and valleys, through to full strip-and-recover re-roofs with new breathable membrane and battens.",
        "intro": ["Most roofs don't need replacing; they need the right repair. A handful of slipped slates, a failed valley or a cracked ridge can be fixed on their own. But when faults are widespread (nails failing across a slope, tiles perishing, battens rotting), repairs just chase the problem around the roof.",
                  "The honest answer about whether to repair or re-roof comes from looking at the roof as a whole."],
        "options": [("Natural slate", "Victorian and Edwardian houses", "Long-lived stone; failures are usually the nails, lead and battens rather than the slate itself."),
                    ("Clay plain tiles", "Interwar and older houses", "Small tiles hung on nibs; frost and age cause cracking; older roofs often lack a membrane."),
                    ("Concrete interlocking tiles", "Post-war homes and many re-roofs", "Heavy and durable; ridge, verge and flashing details are the usual weak points."),
                    ("Clay or concrete pantiles", "Extensions, outbuildings, some houses", "Large S-shaped tiles; laps and verges need care in exposed spots.")],
        "process": [("Scaffold and protect", "Safe access, with gutters, paths and gardens protected."),
                    ("Strip", "The old covering comes off; sound slates or tiles are set aside for reuse where appropriate."),
                    ("Check the timbers", "Rafters and fascias are checked, and any rot is dealt with before anything goes back on."),
                    ("Membrane and battens", "New breathable membrane and treated battens set out for the new covering."),
                    ("Cover and detail", "Tiles or slates laid, then ridges, hips, verges, valleys and flashings finished."),
                    ("Clear up", "Waste removed and the site left clean.")],
        "repair_or_replace": "Repair when the problem is local and the covering is sound. Re-roof when faults are spread across the roof, the battens or membrane have failed, or you're paying for repeated repairs. A roof that has been patched repeatedly often costs more over a few years than re-covering it once.",
        "cost_factors": ["Roof size, height and pitch", "Scaffolding", "The covering: natural slate, clay or concrete", "How much sound material can be reused", "Timber repairs found once the roof is stripped", "Details such as valleys, dormers, chimneys and roof windows"],
        "prevent": ["Replace slipped tiles and slates straight away", "Keep valleys and gutters clear", "Have ridges and verges checked every few years", "Clear heavy moss before it lifts tile edges"],
        "includes": ["Replacing slipped, cracked or missing tiles and slates", "Ridge, hip and verge repairs", "Valley repairs", "Strip and re-roof with new breathable membrane and battens", "Porch, bay and canopy roofs", "Diagnosing leaks"],
        "signs": ["Damp patches on ceilings or in the loft after rain", "Tiles or slates in the gutter or on the ground", "Daylight visible through the roof from the loft", "Loose or cracked ridge tiles", "Moss lifting the tile edges", "A dipping or sagging roof line"],
        "faqs": [
            ("Can a leaking roof in {area} be repaired rather than replaced?", "Often, yes. Many leaks come from a few slipped tiles, a failed valley or flashing, or a blocked gutter rather than the whole roof."),
            ("Can my existing slates be reused?", "Sound natural slates can often be reused, with any shortfall made up from matching reclaimed slate."),
            ("Do I need Building Regulations approval to re-roof?", "In England, re-covering a significant part of a roof (commonly more than a quarter of it) can fall under Building Regulations, including insulation requirements, and a heavier covering can need a structural check. Check with Building Control before a full re-roof."),
            ("Do roof repairs in {area} need scaffolding?", "It depends on the height, access and the work. Some repairs can be done safely from ladders and roof ladders; chimney work and re-roofs usually need scaffolding. A B90 customer noted the team “sorted everything from getting scaffold” through to clearing the waste."),
            ("What's the difference between a slate and a tiled roof?", "Natural slate is thin split stone laid in overlapping courses, common on Victorian and Edwardian houses. Clay and concrete tiles are thicker and were used widely on interwar and post-war homes. Repairs should match the existing material."),
        ],
        "projects": ["reroof", "canopy"], "quote": "roofing",
    },
    {
        "slug": "chimney-repair", "trade": "Roofer", "matrix": True, "hero": "chim_a",
        "name": "Chimney repair & rebuilding", "h1": "Chimney repair & rebuilding", "kw": "Chimney Repair",
        "summary": "Repointing, rebuilding, flaunching, pots and flashing on chimney stacks.",
        "cta": "Chimney looking tired? Send a photo from the ground.",
        "answer": "RJR Home Improvements repairs, repoints and rebuilds chimney stacks in {area}: eroded mortar, loose or broken brickwork, cracked flaunching, failed lead flashing and damaged pots. A chimney sits between bricklaying and roofing, and we cover both trades.",
        "intro": ["A chimney stack is the most exposed brickwork on a house. It takes wind and rain on every side, and when it fails it does so from the top down: flaunching cracks, pointing washes out, bricks loosen, and water finds its way into the chimney breast below.",
                  "The chimney on this page shows the whole story: open joints, displaced bricks and a cracked pot before, then rebuilt courses, fresh pointing and new flaunching after."],
        "anatomy": [("Pots", "Clay or stone terminals on top of each flue."),
                    ("Flaunching", "The sloped mortar cap around the pots that sheds water off the top of the stack."),
                    ("Pointing", "The mortar in the joints between bricks, which is designed to wear before the bricks do."),
                    ("Oversailing courses", "Projecting brick courses near the top that throw water clear of the stack below."),
                    ("Flashing and soakers", "Lead pieces that seal the joint where the stack passes through the roof."),
                    ("Cowls and caps", "Fittings on or over pots that keep rain and birds out of the flue.")],
        "process": [("Scaffold", "A safe working platform around the stack."),
                    ("Assess", "Pointing, brickwork, flaunching, pots and flashing checked close up."),
                    ("Take down if needed", "Loose or unsound brickwork removed down to a sound course."),
                    ("Rebuild and repoint", "Matching bricks relaid and joints repointed."),
                    ("Flaunch and flash", "New flaunching around the pots, and lead flashing where the stack meets the roof."),
                    ("Pots and caps", "Pots reset or replaced, and unused flues capped.")],
        "repair_or_replace": "If the bricks are sound and only the joints have eroded, repointing is enough. If bricks are cracked, spalled or loose, or the stack leans, the affected courses need taking down and rebuilding. The before-and-after on this page needed rebuilding through the oversailing courses.",
        "cost_factors": ["Scaffolding, usually needed for chimney work", "Height of the stack and number of pots", "How much brickwork needs rebuilding", "Matching bricks", "Lead flashing work"],
        "prevent": ["Look at the stack from the ground once a year", "Deal with cracked flaunching early; it's the stack's roof", "Remove plants growing from joints", "Cap unused flues, with ventilation"],
        "includes": ["Repointing chimney stacks", "Rebuilding stacks and oversailing courses", "Re-flaunching around the pots", "Replacing chimney pots", "Lead flashing where the stack meets the roof", "Building new chimney stacks"],
        "signs": ["Crumbling or missing mortar between the bricks", "Cracked or broken flaunching around the pots", "Plants or heavy lichen growing on the stack", "A leaning stack or loose bricks", "Damp on the chimney breast inside", "Debris falling into the fireplace or gutter"],
        "faqs": [
            ("Does my chimney need repointing or rebuilding?", "If the bricks are sound and only the mortar has eroded, repointing is usually enough. Cracked, spalled or loose bricks, or a leaning stack, mean part of it needs rebuilding. A stack has to be seen close up to be sure."),
            ("Why is my chimney breast damp?", "Common causes are failed flashing where the stack meets the roof, eroded pointing, cracked flaunching, or an open flue letting rain straight in. Each needs a different fix, so it's worth diagnosing first."),
            ("Do chimney repairs in {area} need scaffolding?", "Almost always. Working on a stack safely needs a platform around it. The chimney photos on this page were taken from the scaffold on the job."),
            ("What is flaunching?", "The sloped mortar cap on top of the stack, around the pots. It sheds rain off the top of the chimney; when it cracks, water gets into the brickwork and down the flue."),
            ("What are the warning signs that a chimney needs urgent attention?", "Loose or fallen bricks, a leaning stack, a cracked or tilting pot, or debris falling into the fireplace. Keep people clear of anything that could fall and get it looked at quickly."),
        ],
        "projects": ["chimney"], "quote": "finish",
    },
    {
        "slug": "flat-roofs", "trade": "Roofer", "matrix": True, "hero": "velux_d",
        "name": "Flat roofs", "h1": "Flat roof repair & replacement", "kw": "Flat Roof Repair & Replacement",
        "summary": "New and repaired flat roofs on extensions, garages, dormers and porches.",
        "cta": "Flat roof ponding or leaking? Send us a photo.",
        "answer": "RJR Home Improvements installs and repairs flat roofs on extensions, garages, dormers and porches in {area}: finding and fixing leaks, replacing failed coverings and rotten decks, and renewing the edge trims, upstands and flashings where the flat roof meets the house.",
        "intro": ["Flat roofs aren't actually flat. They need a slight fall to drain, and a sound deck, a well-laid covering and properly detailed edges. Most flat roof problems come from one of those being wrong.",
                  "The edges matter most: the upstand and flashing against the house wall, the trim along the gutter, and the outlets. That's where most leaks start."],
        "options": [("EPDM rubber", "Simple shapes, extensions and garages", "A single sheet of synthetic rubber with few joints."),
                    ("GRP fibreglass", "Roofs with detail, or light foot traffic", "Laid wet and cured into a seamless, hard-wearing surface."),
                    ("Felt (torch-on or mineral)", "Familiar, adaptable systems", "Built up in layers; quality varies widely between systems.")],
        "warm_cold": "In a warm roof the insulation sits on top of the deck, under the waterproof covering, so the structure stays warm. In a cold roof the insulation sits between the joists and the void above it must be ventilated. When a flat roof is replaced it's often the right time to think about insulation, which can bring Building Regulations into play.",
        "process": [("Strip", "The old covering comes off, down to the deck."),
                    ("Check the deck", "Soft or rotten boards are replaced; the fall is checked."),
                    ("Insulate if needed", "Insulation added where the roof calls for it."),
                    ("Cover", "The new covering is laid to the manufacturer's method."),
                    ("Edges and upstands", "Trims, upstands and wall flashings finished properly."),
                    ("Outlets", "Water led cleanly into the gutter or outlet.")],
        "repair_or_replace": "A single split, a failed seam or a lifted edge can usually be repaired. Repeated leaks, widespread blistering, ponding or a soft deck mean the covering is finished, and replacing it stops the cycle of patching.",
        "cost_factors": ["Roof area and access", "Whether the deck needs replacing", "The covering system", "Insulation", "Edge details, upstands and outlets"],
        "prevent": ["Keep outlets and gutters clear", "Sweep off leaves and debris", "Avoid walking on it unless the covering is designed for it", "Check edges and flashings each spring"],
        "includes": ["Leak repairs", "Replacing failed flat roof coverings", "Replacing rotten decking boards", "Edge trims, upstands and wall flashings", "Garage, extension, dormer and porch roofs", "Outlets and drainage into the gutters"],
        "signs": ["Water still ponding days after rain", "Blistering, splitting or cracking on the surface", "Soft or spongy areas underfoot", "Staining on the ceiling below", "Lifted edges or failed flashing at the wall"],
        "faqs": [
            ("What types of flat roof are there?", "Common systems include EPDM rubber membranes, GRP fibreglass and felt (torch-on or mineral felt). Each suits different sizes, details and budgets. We'll talk it through once we've seen your roof."),
            ("Why does water pond on my flat roof?", "A flat roof needs a slight fall to drain. If the deck has sagged, or the roof was laid too flat, water sits on it and speeds up wear."),
            ("Can my flat roof be repaired, or does it need replacing?", "Localised damage such as a split, a failed seam or a lifted edge can often be repaired. If the deck has gone soft or water has been getting in for a long time, replacing the covering and the damaged boards is usually the better option."),
            ("What's the difference between a warm roof and a cold roof?", "A warm roof has insulation on top of the deck, under the covering. A cold roof has insulation between the joists and needs ventilating above it."),
            ("Do I need permission to replace a flat roof in {area}?", "Replacing a covering like for like generally doesn't need planning permission. Changing the roof's shape or height might, conservation areas carry extra controls, and adding insulation can involve Building Regulations. If you're altering anything, check with {council} first."),
        ],
        "projects": ["velux"], "quote": "leak",
    },
    {
        "slug": "guttering", "trade": "Roofer", "hero": "fascia_a",
        "name": "Guttering & downpipes", "h1": "Guttering & downpipes", "kw": "Guttering Repairs & Gutter Clearing",
        "summary": "Gutter clearing, leaking joints, sagging runs and new downpipes.",
        "cta": "Gutters overflowing? Send a photo.",
        "answer": "RJR Home Improvements clears, repairs and replaces gutters and downpipes in {area}: leaking joints, sagging runs, blocked outlets and cracked pipes, so rainwater leaves the roof and gets away from your walls. No job is too small; gutter clearances are part of what we do.",
        "intro": ["Gutters are the cheapest part of a roof to maintain and one of the most expensive to ignore. An overflowing gutter soaks the wall below, pushes water behind the fascia and into the roof edge, and over time causes damp inside.",
                  "On the house in our photos, the old black gutters and downpipes were replaced with white as part of new fascias and bargeboards."],
        "options": [("uPVC", "Most modern homes", "Light and low-maintenance; joint seals age and are the usual leak point."),
                    ("Cast iron", "Period properties", "Very durable if painted and maintained; heavy, and sections crack if neglected."),
                    ("Aluminium", "Where a slimmer, stronger profile suits", "Light and strong, with fewer joints on seamless runs.")],
        "process": [("Clear", "Debris removed from gutters, outlets and downpipes."),
                    ("Test", "Water run through to find leaks and back-falls."),
                    ("Repair", "Joints resealed or replaced, brackets refixed to the right fall."),
                    ("Replace", "Worn sections or whole runs replaced where needed.")],
        "cost_factors": ["Length of run and height", "Access and whether scaffolding is needed", "Material", "Condition of the fascia boards behind"],
        "prevent": ["Clear gutters at least once a year, more often under trees", "Fit leaf guards where trees overhang", "Check joints for drips during rain", "Keep downpipe shoes and drains clear"],
        "includes": ["Gutter clearing", "Resealing or replacing leaking joints", "Re-fixing sagging runs and brackets", "Replacing gutters and downpipes", "Clearing blocked outlets and swan necks", "Gutters on extensions, porches and garages"],
        "signs": ["Overflowing in heavy rain", "Drips from the joints", "Green streaks or damp patches on the brickwork", "Plants growing in the gutter", "Gutters pulling away from the fascia"],
        "faqs": [
            ("Do you take on small jobs like gutter clearing in {area}?", "Yes. Our work runs from odd jobs as small as garden and gutter clearances to full refurbishments."),
            ("How often should gutters be cleared?", "At least once a year, usually after autumn leaf fall, and more often under trees."),
            ("Can a blocked gutter cause a leak inside?", "Yes. A blocked or back-falling gutter can push water behind the fascia and into the wall or roof edge. It's one of the first things to check when tracing a leak."),
            ("What if my gutter is shared with a neighbour?", "Terraced and semi-detached houses often share gutter runs and downpipes, so the first job is finding where the fault actually is. A B30 customer had been told their neighbours would need new gutters too; they were “pleasantly surprised how straightforward he made it”."),
            ("Why do gutters overflow at the corners?", "Corners and outlets collect debris, and water there moves fastest. If the gutter is blocked or its fall is wrong, water jumps it."),
        ],
        "projects": ["fascias"], "quote": "gutters",
    },
    {
        "slug": "fascias-soffits", "trade": "Roofer", "hero": "fascia_a",
        "name": "Fascias, soffits & bargeboards", "h1": "Fascias, soffits & bargeboards", "kw": "Fascias, Soffits & Bargeboards",
        "summary": "uPVC and timber fascias, soffits, bargeboards and cladding.",
        "cta": "Rotten boards or tired trims? Send a photo.",
        "answer": "RJR Home Improvements replaces and repairs fascias, soffits, bargeboards and cladding in {area}, in uPVC or timber, and refits the gutters that hang from them. Where the timber behind old boards has rotted, that is dealt with before the new boards go on.",
        "intro": ["Fascias carry the gutters and close off the ends of the rafters. Soffits close the underside of the eaves. Bargeboards finish the sloping edges of gables. Together they're the roofline, and when they rot, water, birds and wasps get into the roof.",
                  "The house in our photos had black gable trims replaced with white decorative uPVC bargeboards on all three gables, with new fascias, gutters and downpipes."],
        "options": [("uPVC", "Most homes", "Little maintenance beyond cleaning; available in decorative profiles and colours."),
                    ("Timber", "Period homes and some conservation areas", "Traditional look; needs regular painting.")],
        "process": [("Remove", "Old boards and gutters taken down."),
                    ("Inspect", "Rafter ends and wall plates checked for rot and repaired."),
                    ("Fit", "New fascias, soffits and bargeboards fixed, with ventilation where the roof needs it."),
                    ("Refit", "Gutters and downpipes refitted or replaced to the right fall.")],
        "cost_factors": ["Length of roofline and number of gables", "Scaffolding", "uPVC or timber, plain or decorative", "Rot in the rafter ends behind", "Whether gutters are replaced at the same time"],
        "prevent": ["Keep timber boards painted", "Keep gutters clear so water doesn't soak the fascia", "Deal with gaps before birds and wasps move in"],
        "includes": ["uPVC fascias, soffits and bargeboards", "Timber fascias, soffits and bargeboards", "Decorative bargeboards", "Wooden and uPVC cladding", "Refitting gutters to new boards"],
        "signs": ["Flaking paint, soft or split timber", "Boards sagging or pulling away", "Birds or wasps getting in at the eaves", "Gutters that won't stay level", "Brittle or discoloured uPVC"],
        "faqs": [
            ("uPVC or timber fascias?", "uPVC needs little more than cleaning. Timber suits older and period houses, and is sometimes preferred in conservation areas, but needs repainting. We fit both."),
            ("Should old fascias be replaced or capped over?", "Capping fits uPVC over the existing timber, which can hide rot that keeps spreading. Full replacement lets the rafter ends and roof edge be checked. The condition of the existing boards decides it."),
            ("Can decorative bargeboards be replaced?", "Yes. The house in our photos had its black gable trims replaced with white decorative uPVC bargeboards on all three gables."),
            ("Do new soffits need ventilation?", "Many roofs rely on eaves ventilation through the soffit to prevent condensation in the loft, so new soffits should keep or add ventilation where the roof needs it."),
        ],
        "projects": ["fascias", "canopy"], "quote": "finish",
    },
    {
        "slug": "velux-windows", "trade": "Roofer", "hero": "velux_a",
        "name": "Velux & roof windows", "h1": "Velux & roof windows", "kw": "Velux & Roof Window Fitting",
        "summary": "New and replacement roof windows, with the flashing that seals them in.",
        "cta": "Want more light, or a leaking Velux fixed? Send a photo.",
        "answer": "RJR Home Improvements fits new Velux and skylight roof windows, and replaces old or leaking ones, in {area}, on loft rooms, extensions and pitched roofs. That includes the flashing kit that seals the window into the tiles or slates.",
        "intro": ["A roof window is the simplest way to bring daylight into a loft room or a single-storey extension. Getting it right is about the opening and the flashing: the rafters are trimmed to take the window, and the flashing kit is matched to the roof covering so water runs round it.",
                  "The extension on this page shows it: stripped to membrane and battens with the opening framed, then re-covered with the new window in place."],
        "options": [("Centre-pivot", "Most rooms", "Opens by pivoting in the middle; easy to clean from inside."),
                    ("Top-hung", "Where you want a clear view out, or escape access", "Opens outwards from the top."),
                    ("Conservation-style", "Period roofs and conservation areas", "Low-profile, slimmer frame designed to suit traditional roofs.")],
        "process": [("Plan", "Size and position agreed, planning checked if needed."),
                    ("Open up", "Tiles or slates removed and rafters trimmed to form the opening."),
                    ("Fit", "Window and flashing kit fitted to suit the roof covering."),
                    ("Make good", "Membrane, battens and tiles made good around the window.")],
        "cost_factors": ["Window size and type", "Roof covering (slate or tile) and matching flashing kit", "Access and scaffolding", "Structural work to trim the opening", "Internal finishing"],
        "prevent": ["Keep the flashing and the gutter above the window clear of debris", "Check seals and hinges each year", "Ventilate rooms to reduce condensation on the glass"],
        "includes": ["New roof windows in pitched roofs", "Replacing old or leaking roof windows", "Flashing kits for tiles and slates", "Trimming the roof structure to form the opening", "Making good membrane, battens and tiles around the window"],
        "signs": ["Leaks or staining around the frame", "Rotten or swollen timber frames", "Misted glazing from failed seals", "A dark room under a pitched roof"],
        "faqs": [
            ("Do roof windows in {area} need planning permission?", "Rooflights are often permitted development if they don't project more than 150mm from the roof slope and aren't higher than the highest part of the roof. Listed buildings and conservation areas are different. Check with {council} before committing."),
            ("Can a Velux go into an existing roof without re-roofing?", "Yes. The tiles or slates around the opening come off, the rafters are trimmed, the window and flashing kit go in, and the roof is made good around it. On the extension shown here the roof was stripped and re-covered at the same time."),
            ("Can an old leaking Velux be replaced with the same size?", "Roof windows come in standard sizes, so a replacement can often go into the existing opening. An unusual or discontinued size may mean adjusting the opening."),
            ("Why is my roof window leaking?", "Usually the flashing, a blocked channel above the window, or failed seals. Older windows can also leak through a rotted frame."),
        ],
        "projects": ["velux"], "quote": "finish",
    },
    {
        "slug": "leadwork", "trade": "Roofer", "hero": "velux_a",
        "name": "Leadwork", "h1": "Leadwork & lead flashing", "kw": "Leadwork & Lead Flashing",
        "summary": "Flashings, soakers, valleys and abutments.",
        "cta": "Lead lifted, split or missing? Send a photo.",
        "answer": "RJR Home Improvements carries out leadwork on roofs in {area}: flashings where roofs meet walls and chimneys, soakers, valleys, and the lead around roof windows, bays and dormers.",
        "intro": ["Lead seals the joints a roof can't cover with tiles: where it meets a wall, a chimney, another slope or a window. It's the detail most leaks trace back to.",
                  "Lead moves with heat and cold, so it has to be cut to sensible lengths, dressed to shape and fixed so it can expand without splitting or pulling loose."],
        "process": [("Remove", "Failed or loose lead taken off."),
                    ("Prepare", "Mortar joints raked out and the surface made sound."),
                    ("Cut and dress", "New lead cut to suitable lengths and dressed to the roof shape."),
                    ("Fix", "Tucked into the mortar joint, wedged and pointed, with laps in the right direction.")],
        "cost_factors": ["Where the lead is and how it's reached", "Length and complexity of the detail", "Scaffolding", "Whether surrounding tiles or brickwork need work"],
        "prevent": ["Look for lead that has lifted after wind", "Keep valleys clear", "Avoid mastic-only repairs; they're temporary"],
        "includes": ["Chimney flashings and soakers", "Wall abutment flashings", "Lead valleys", "Bay and dormer leadwork", "Lead around roof windows"],
        "signs": ["Damp where a roof meets a wall or chimney", "Lead lifted by wind or pulled out of its joint", "Split or cracked lead", "Missing lead"],
        "faqs": [
            ("Why does lead flashing fail?", "Lead can split if pieces are too long, lift if it isn't dressed and fixed properly, or pull out of the mortar joint it's tucked into. All of these let water in where roofs meet walls."),
            ("Is mastic or flashing tape a proper repair?", "They're short-term fixes. Properly dressed lead, tucked into the mortar joint, lasts far longer."),
            ("What are soakers?", "Individual lead pieces laid under each course of tiles or slates alongside a wall or chimney, covered by a step flashing above."),
        ],
        "projects": ["velux", "chimney"], "quote": "diagnosis",
    },
    {
        "slug": "roof-cleaning", "trade": "Roofer", "hero": "tile_a",
        "name": "Roof cleaning", "h1": "Roof cleaning & moss removal", "kw": "Roof Cleaning & Moss Removal",
        "summary": "Moss and debris cleared from roofs, valleys and gutters.",
        "cta": "Roof covered in moss? Send a photo.",
        "answer": "RJR Home Improvements cleans roofs in {area}, clearing moss and debris from tiles, valleys and the gutters they end up in, and checking the roof underneath while we're up there.",
        "intro": ["Moss on a roof is more than a cosmetic problem. It holds water against the tiles, lifts their edges, and washes down to block gutters, valleys and outlets.",
                  "Cleaning is also a chance to look at the roof properly: slipped tiles, cracked ridges and worn flashings show up once the moss is off."],
        "process": [("Clear", "Moss and debris removed from the tiles."),
                    ("Valleys and gutters", "Valleys, gutters and outlets cleared of what comes down."),
                    ("Check", "Tiles, ridges and flashings looked over and any faults reported.")],
        "cost_factors": ["Roof size and access", "How heavy the moss is", "Scaffolding or access equipment", "Any repairs found underneath"],
        "prevent": ["Keep overhanging branches cut back", "Clear gutters every year", "Deal with slipped tiles, which hold moss and water"],
        "includes": ["Moss removal from tiles", "Clearing debris from valleys", "Gutter clearing afterwards", "A look over the roof for faults"],
        "signs": ["Thick moss on the tiles", "Moss clumps in gutters and on paths", "Blocked valleys and outlets"],
        "faqs": [
            ("Is moss bad for a roof?", "Heavy moss holds water against the tiles and can lift their edges. When it washes off, it blocks gutters and outlets."),
            ("Is pressure washing safe for roof tiles?", "High pressure can strip the surface of older tiles and force water up under them. Gentler methods are usually better for the roof."),
            ("Will moss come back?", "On shaded, north-facing or tree-covered roofs it tends to return over time. Regular gutter clearing and cutting back branches slow it down."),
        ],
        "projects": [], "quote": "tidy",
    },
    {
        "slug": "roof-insulation", "trade": "Roofer", "hero": "velux_d",
        "name": "Roof insulation", "h1": "Roof & loft insulation", "kw": "Roof & Loft Insulation",
        "summary": "Insulation in lofts and roofs, including during re-roofing.",
        "cta": "Cold top floor? Let's look at the roof.",
        "answer": "RJR Home Improvements fits roof insulation in {area}, in lofts and roofs, including as part of re-roofing, flat roof replacement, loft conversion and extension work.",
        "intro": ["Heat rises, and an under-insulated roof is where much of it goes. Insulation can go between and over the joists in a cold loft, or between and under the rafters where the roof space is used.",
                  "Ventilation matters as much as insulation: a roof that's insulated without thought for airflow can trap moisture and cause condensation."],
        "process": [("Assess", "What's there now, how the roof space is used, and how it's ventilated."),
                    ("Prepare", "Clearing access and dealing with any damp or roof faults first."),
                    ("Insulate", "Insulation fitted at the joists or rafters to suit the space."),
                    ("Ventilate", "Airflow kept or added at the eaves and ridge where needed.")],
        "cost_factors": ["Loft or rafter-level insulation", "Access and existing materials to remove", "Whether it's part of a re-roof or conversion"],
        "prevent": ["Keep eaves vents clear of insulation", "Don't block airflow when boarding a loft", "Fix leaks before insulating"],
        "includes": ["Loft insulation", "Insulation during re-roofing", "Flat roof insulation", "Insulation in loft conversions and extensions"],
        "signs": ["A cold top floor", "Thin or patchy loft insulation", "Condensation in the loft"],
        "faqs": [
            ("Can insulation be added when a roof is replaced?", "Yes. A re-roof or new flat roof is a good time, because the structure is open."),
            ("Why is there condensation in my loft?", "Usually a mix of warm, moist air from the house and poor ventilation in the roof space. Insulation that blocks the eaves vents can make it worse."),
            ("Does roof insulation need Building Regulations approval?", "Insulation fitted as part of a re-roof, conversion or extension usually falls within Building Regulations. Topping up loft insulation on its own generally doesn't need approval."),
        ],
        "projects": [], "quote": "roofing",
    },
]

# Grouped pages: honest single pages for trades where there's less to say.
GROUPS = [
    {
        "slug": "specialist-roofing", "trade": "Roofer", "hero": "tile_v",
        "name": "Zinc, metal & thatched roofs", "h1": "Zinc, metal & thatched roofs", "kw": "Zinc, Metal & Thatched Roofing",
        "summary": "Zinc and metal roofing, metalwork and thatched roof work.",
        "cta": "Specialist roof? Send us photos and details.",
        "answer": "Alongside slate, tile and flat roofs, RJR Home Improvements works on zinc and metal roofs, with metalwork under our blacksmith and metal worker trade, and carries out thatched roof work in {area}.",
        "sections": [
            ("Zinc & metal roofs", ["Zinc and metal roofing is listed under both our roofing and our blacksmith and metal worker trades. Metal roofs rely on well-formed seams, laps and fixings; problems usually show as corrosion, staining, or leaks at laps and fixings."],
             ["Zinc roofing", "Metal roofing", "Metalwork"]),
            ("Thatched roofs", ["Thatched roof work is one of the roofing trades we list. Send photos and details of your roof on WhatsApp and we'll come back to you."], []),
        ],
        "faqs": [("What goes wrong on metal roofs?", "Corrosion, failed seams and laps, and loosened fixings. Most leaks on metal roofs trace back to one of these.")],
    },
    {
        "slug": "brickwork", "trade": "Bricklayer", "hero": "chim_b2",
        "name": "Brickwork & stonework", "h1": "Brickwork, repointing & stonework", "kw": "Brickwork, Repointing & Stonework",
        "summary": "Repointing, garden walls, stonework, stone cladding and pizza ovens.",
        "cta": "Brickwork job? Send a photo.",
        "answer": "RJR Home Improvements carries out bricklaying and stonework in {area}: repointing walls and chimneys, building and rebuilding garden walls, stonework and stone cladding, and pizza ovens.",
        "sections": [
            ("Pointing & repointing", ["Mortar joints are meant to wear before the bricks do. When they erode, rain gets into the wall and the bricks start to suffer. Repointing means raking out the old mortar to a sound depth and refilling the joints with a mortar that suits the wall."],
             ["Repointing walls", "Repointing chimney stacks", "Repointing garden walls"]),
            ("Garden walls", ["New garden walls, and rebuilding walls that lean, bulge or have lost their copings."], ["New garden walls", "Rebuilding leaning or damaged walls", "Copings and repointing"]),
            ("Stonework & stone cladding", ["Stonework and stone cladding, alongside our brickwork."], ["Stonework", "Stone cladding"]),
            ("Pizza ovens", ["Built pizza ovens, as part of our bricklaying work."], ["Pizza oven builds"]),
        ],
        "faqs": [("How do I know if my walls need repointing?", "Mortar that is crumbling, recessed well behind the brick face or missing, plants growing from joints, or damp patches inside on the other side of the wall."),
                 ("Does the mortar type matter?", "Yes. Older brickwork usually needs a softer mortar than modern walls, so the mortar wears rather than the bricks.")],
    },
    {
        "slug": "building-work", "trade": "Builder", "hero": "leanto_d",
        "name": "Building & home improvements", "h1": "Building work & home improvements", "kw": "Builders & Home Improvements",
        "summary": "Extensions, loft and garage conversions, insulation, damp and mould, cladding.",
        "cta": "Planning building work? Send details and photos.",
        "answer": "RJR Home Improvements covers the whole building sector in {area}: house extensions, loft conversions, garage conversions, cavity wall insulation, mould and damp control, cladding, and home improvements from odd jobs to full refurbishments.",
        "sections": [
            ("House extensions", ["As roofers as well as builders, the roof over an extension, flat or pitched, with or without roof windows, is part of the same job."], ["House extensions", "Pitched and flat extension roofs", "Roof windows in extensions"]),
            ("Loft conversions", ["Loft conversions, including the roof windows, roof insulation and roofing work that go with them."], ["Loft conversions", "Roof windows", "Roof insulation"]),
            ("Garage conversions", ["Converting garages into living space."], ["Garage conversions"]),
            ("Cavity wall insulation", ["Cavity wall insulation."], ["Cavity wall insulation"]),
            ("Mould & damp control", ["Because we're roofers, bricklayers and builders, damp can be followed back to its source (a roof, gutter, chimney or wall) and fixed there, rather than treated only on the surface."], ["Mould and damp control", "Roof, gutter and chimney leaks behind damp", "Repointing to stop penetrating damp"]),
            ("Cladding", ["Timber and uPVC cladding."], ["Cladding"]),
            ("Home improvements", ["From odd jobs as small as garden and gutter clearances to full refurbishments and replacements from top to bottom of your home, like the new lean-to porch roof shown here."], ["Odd jobs", "Garden and gutter clearances", "Porch and canopy roofs", "Full refurbishments and replacements"]),
        ],
        "faqs": [("Can damp inside come from the roof?", "Yes. Leaking roofs, blocked gutters, failed flashing and eroded pointing on chimneys and walls all let water into a house."),
                 ("Do you take on small jobs?", "Yes, from garden and gutter clearances to full refurbishments.")],
        "projects": ["leanto"],
    },
]

# ==========================================================================
# AREAS
# ==========================================================================
BCC = "Birmingham City Council"
SMBC = "Solihull Metropolitan Borough Council"

AREAS = [
    {
        "slug": "edgbaston", "quote": "diagnosis", "name": "Edgbaston", "pcs": ["B15", "B16"], "council": BCC, "hero": "chim_a",
        "stock": "Edgbaston is dominated by large Georgian, Regency and Victorian villas, much of it on the Calthorpe Estate and inside the Edgbaston Conservation Area, alongside later flats and twentieth-century infill.",
        "planning": "Much of Edgbaston is a conservation area and a lot of it sits on the Calthorpe Estate, so like-for-like materials are normally expected on visible roofs and some work may need consent from the council or the estate. Check before work starts.",
        "features": ["slate", "stacks", "parapets", "trees", "conservation", "flat_ext"],
        "near": ["harborne", "selly-oak", "moseley"], "reviews": ["ann-b17"],
        "faqs": [
            ("What should owners of period houses in Edgbaston know before roof work?", "Much of Edgbaston is in a conservation area and on the Calthorpe Estate. Like-for-like repairs with natural slate and lead are the norm. If materials or appearance will change, check with Birmingham City Council and, where it applies, the estate first."),
            ("Why do large Edgbaston roofs leak inside the walls?", "Many have parapet or box gutters hidden behind the roof edge. When an outlet blocks or the lining splits, water spills into the wall instead of over the edge."),
            ("Are old cast-iron gutters worth keeping?", "On period houses they often are. Sound cast iron can be cleared, resealed and repainted; badly cracked sections can be replaced to suit the house."),
        ],
    },
    {
        "slug": "harborne", "quote": "finish", "name": "Harborne", "pcs": ["B17"], "council": BCC, "hero": "fascia_a",
        "stock": "Harborne mixes Victorian and Edwardian terraces around the High Street with interwar semis further out, and includes the Moor Pool garden suburb.",
        "planning": "Moor Pool and parts of the older village are conservation areas, where visible roof changes may need consent from Birmingham City Council. Elsewhere, like-for-like repairs are usually straightforward.",
        "features": ["slate", "clay", "shared_stacks", "outriggers", "flat_ext", "hips", "conservation"],
        "near": ["edgbaston", "selly-oak", "northfield"], "reviews": ["ann-b17"],
        "faqs": [
            ("Have you worked in Harborne?", "One of our recent verified Rated People reviews is from B17: “I believe that he diagnosed correctly the problem with the roof.”"),
            ("My terrace shares a valley with next door. Who repairs it?", "A valley between two roofs usually serves both houses, so a lasting repair often means working on both sides. Speak to your neighbour early."),
            ("Is Moor Pool a conservation area?", "Yes. The Moor Pool estate is a conservation area with controls on visible changes. Like-for-like roof repairs are normally fine; check with Birmingham City Council before changing materials."),
        ],
    },
    {
        "slug": "moseley", "quote": "leak", "name": "Moseley", "pcs": ["B13"], "council": BCC, "hero": "chim_b1",
        "stock": "Moseley is known for Victorian and Edwardian villas and terraces around Moseley Village, many of them within the Moseley and St Agnes conservation areas.",
        "planning": "Large parts of Moseley are conservation areas, so matching original materials on visible roofs matters, and some changes may need consent from Birmingham City Council.",
        "features": ["slate", "stacks", "trees", "conservation", "canopies", "flat_ext", "outriggers"],
        "near": ["kings-heath", "edgbaston", "hall-green"], "reviews": ["lewis-b30"],
        "faqs": [
            ("Is my Moseley street in a conservation area?", "Moseley and St Agnes are both conservation areas and cover a large part of the district. Birmingham City Council publishes the boundaries, so check the map for your street."),
            ("Can decorative ridge tiles and finials be repaired like for like?", "They should be. Terracotta ridge tiles and finials on Victorian roofs can be re-bedded, or matched with reclaimed or reproduction pieces."),
            ("Why do Moseley gutters block so quickly?", "Mature trees. Large period roofs shed a lot of water into gutters that fill with leaves every autumn, so outlets and valleys block quickly."),
        ],
    },
    {
        "slug": "kings-heath", "quote": "gutters", "name": "Kings Heath", "pcs": ["B14"], "council": BCC, "hero": "velux_a",
        "stock": "Kings Heath is mostly Victorian and Edwardian terraces and semis around the High Street and York Road, with interwar semis on the outer roads.",
        "planning": "Before changing how a roof looks, check with Birmingham City Council whether your street is in a conservation area. Like-for-like repairs are usually straightforward.",
        "features": ["slate", "clay", "shared_stacks", "outriggers", "flat_ext", "hips", "canopies"],
        "near": ["moseley", "stirchley", "hall-green"], "reviews": ["lewis-b30"],
        "faqs": [
            ("Where do leaks usually start on a Kings Heath terrace?", "At the back: the valley between neighbouring back additions and the flashing where a flat-roofed kitchen extension meets the house."),
            ("Do I need planning permission for roof repairs in Kings Heath?", "Like-for-like repairs generally don't. Changing the look of the roof, adding dormers or putting roof windows on the front may need permission or fall under permitted development. Check with Birmingham City Council."),
            ("Can a loft in a Kings Heath terrace take roof windows?", "Rear-slope roof windows are a common way to light a loft room in a terrace without changing the front."),
        ],
    },
    {
        "slug": "hall-green", "quote": "roofing", "name": "Hall Green", "pcs": ["B28"], "council": BCC, "hero": "canopy_d",
        "stock": "Hall Green is largely 1920s and 1930s semi-detached and detached houses, many with bay windows and hipped roofs, along and off the Stratford Road.",
        "planning": "Before changing how a roof looks, check with Birmingham City Council whether any conservation-area controls apply to your street.",
        "features": ["clay", "concrete", "hips", "canopies", "shared_stacks", "flat_ext", "garages"],
        "near": ["kings-heath", "moseley", "shirley"], "reviews": ["matthew-b90"],
        "faqs": [
            ("Why do the hips on my 1930s house keep losing tiles?", "Hip and ridge tiles on interwar roofs are bedded in mortar that has had decades to crack. Re-bedding them, or fitting a dry-fixed system, secures them."),
            ("Can the original clay tiles on a Hall Green semi be kept?", "Where they're sound, yes, with local repairs using matched reclaimed tiles. Where many are cracked or the battens have gone, re-roofing with a new membrane is the longer-term fix."),
            ("Is the bay window roof part of the main roof?", "Usually it's a separate small roof with its own covering and flashing, and it can be repaired on its own."),
        ],
    },
    {
        "slug": "shirley", "quote": "scaffold", "name": "Shirley", "pcs": ["B90"], "council": SMBC, "hero": "tile_a",
        "stock": "Shirley, in Solihull borough, is mostly interwar and post-war semis and detached houses along and off the Stratford Road, with later estates and plenty of garages, porches and single-storey extensions.",
        "planning": "Shirley is in Solihull borough, so planning questions go to Solihull Metropolitan Borough Council.",
        "features": ["concrete", "hips", "canopies", "flat_ext", "garages", "dryfix"],
        "near": ["solihull", "hall-green"], "reviews": ["matthew-b90"],
        "faqs": [
            ("Have you worked in Shirley?", "One of our recent verified Rated People reviews is from B90: “Ryan and his team did great work.”"),
            ("Which council handles planning in Shirley?", "Shirley is in Solihull borough, so Solihull Metropolitan Borough Council."),
            ("Our garage roof keeps leaking. Patch or replace?", "If it's leaking in more than one place, or the deck feels soft, the covering has reached the end of its life and replacement is the lasting fix."),
        ],
    },
    {
        "slug": "solihull", "quote": "roofing", "name": "Solihull", "pcs": ["B91", "B92", "B93"], "council": SMBC, "hero": "fascia_a",
        "stock": "Solihull borough runs from Victorian and Edwardian houses near the town centre to large interwar and post-war detached homes, and newer estates towards Knowle and Dorridge.",
        "planning": "Solihull Metropolitan Borough Council handles planning, and parts of the borough, including Knowle, are conservation areas.",
        "features": ["concrete", "dryfix", "slate", "stacks", "flat_ext", "trees", "conservation"],
        "near": ["shirley", "hall-green"], "reviews": ["matthew-b90"],
        "faqs": [
            ("Are there conservation areas in Solihull?", "Yes, including Knowle. Solihull Metropolitan Borough Council publishes the boundaries."),
            ("My newer house has plastic caps along the roof edge. What are they?", "A dry verge system: caps that clip or screw over the tile edges instead of mortar. If one comes loose it can usually be refixed or replaced."),
            ("Do larger houses need scaffolding for roof work?", "Most full roof and chimney work on two-storey and larger houses needs scaffolding for safe access; small repairs may not."),
        ],
    },
    {
        "slug": "stirchley", "quote": "leak", "name": "Stirchley", "pcs": ["B30"], "council": BCC, "hero": "fascia_b",
        "stock": "Stirchley is mostly Victorian and Edwardian terraced housing along and off the Pershore Road, next to Bournville and Cotteridge.",
        "planning": "Homes on the Bournville Village Trust estate next door are covered by the Trust's scheme of management, so external changes there may need the Trust's consent as well as the council's.",
        "features": ["slate", "shared_stacks", "outriggers", "flat_ext"],
        "near": ["kings-heath", "selly-oak", "northfield"], "reviews": ["lewis-b30"],
        "faqs": [
            ("Our gutter is shared with the neighbours. Can the leak be fixed without replacing theirs?", "Often. A B30 customer had been told their neighbours would need new gutters and they'd need scaffolding; Ryan “fixed the persistent leak we've had for a good price”."),
            ("Is my home on the Bournville Village Trust estate?", "Parts of the area around Bournville are. If yours is, the Trust's consent may be needed for external changes as well as the council's."),
            ("Where do leaks usually start on a Stirchley terrace?", "At the rear: the valley between back additions, the flashing where a flat-roofed kitchen meets the wall, and shared gutter outlets."),
        ],
    },
    {
        "slug": "selly-oak", "quote": "fast", "name": "Selly Oak", "pcs": ["B29"], "council": BCC, "hero": "velux_d",
        "stock": "Selly Oak has Victorian terraces around the Bristol Road and the university, many of them rented, plus interwar semis on the surrounding roads.",
        "planning": "If you let a property here, fixing roof and gutter defects early helps keep damp and mould out of tenants' rooms.",
        "features": ["slate", "shared_stacks", "outriggers", "flat_ext", "rented"],
        "near": ["harborne", "edgbaston", "stirchley", "northfield"], "reviews": ["lewis-b30"],
        "faqs": [
            ("I'm a landlord in Selly Oak. How quickly should a roof leak be fixed?", "As soon as possible. Landlords are generally responsible for keeping the structure and exterior, including the roof and gutters, in repair, and leaks quickly lead to damp and mould."),
            ("What roof problems are common on Selly Oak terraces?", "Slipped slates, leaking valleys between back additions, shared stacks losing their pointing, and flat-roofed rear extensions leaking at the wall."),
            ("Can you arrange access with tenants?", "Send the photos with the name and number of whoever should be contacted for access."),
        ],
    },
    {
        "slug": "northfield", "quote": "tidy", "name": "Northfield", "pcs": ["B31"], "council": BCC, "hero": "tile_v",
        "stock": "Northfield is largely interwar and post-war semi-detached housing, with older terraces near the Bristol Road and the village centre.",
        "planning": "Before changing how a roof looks, check with Birmingham City Council; like-for-like repairs are usually simpler.",
        "features": ["concrete", "hips", "canopies", "shared_stacks", "flat_ext", "garages"],
        "near": ["selly-oak", "stirchley", "harborne"], "reviews": ["john-b31"],
        "faqs": [
            ("Have you worked in Northfield?", "One of our recent verified ratings on Rated People is from B31."),
            ("My hipped roof is losing ridge tiles. Can it be dry-fixed?", "Often, yes. Mortar-bedded ridges and hips can be replaced with a mechanically fixed dry system, or re-bedded in fresh mortar."),
            ("Why is the porch roof on my semi leaking?", "Porch and bay canopies have their own flashing to the wall, which often fails before the main roof does."),
        ],
    },
]
